name = "stefansarya/socketio_client"
description = "Simple library for connecting to Socket.io server for Roblox and Lune environment."
repository = "https://github.com/StefansArya/luau-socket.io-client"
version = "0.1.1"
authors = ["stefansarya"]
license = "MIT"
includes = [
  "pesde.toml",
  "README.md",
  "LICENSE",
  "dist/*.lua",
]

[target]
environment = "roblox"
lib = "dist/socketio.lua"
build_files = ["dist"]

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"